### ISSUE TITLE
希望在this.edit().then()之中，添加一个类似于afterOpened的方法，使可以获取加载数据完成的事件。

### ISSUE THREAD

**Issue by yuanyc-cityfun** [iamoldli/NetModular.UI#8]
https://github.com/iamoldli/NetModular.UI/blob/0ac6605ec7af09e763538957fab7228ec3888d0f/packages/mixins/components/form-save.js#L98

**Comment by iamoldli** [comment]
新增了一个`afterEdit`方法并发布了2.0.4的包
